services:
  semaphore:
    restart: unless-stopped
    ports:
      - 3010:3000
    image: semaphoreui/semaphore:latest
    volumes:
      - semaphore-config:/etc/semaphore # config.json location
      - semaphore-database:/var/lib/semaphore # database.boltdb location (Not required if using mysql or postgres)
    environment:
      - SEMAPHORE_DB_DIALECT=bolt
      - SEMAPHORE_ADMIN_PASSWORD=winterfest
      - SEMAPHORE_ADMIN_NAME=echo
      - SEMAPHORE_ADMIN_EMAIL=echopossum@gmail.com
      - SEMAPHORE_ADMIN=""
      - TZ=America/NewYork

volumes:
  semaphore-config:
    driver: local
  semaphore-database:
    driver: local
